---
# tasks file for debian_management
  - name: "Setup S1 for Root"
    become: yes
    become_user: root
    tags: example1
    lineinfile:
      path: /root/.bashrc
      line: 'PS1="\n\[\033[38;5;196m\](っ▀¯▀)つ\[\033[38;5;196m\]@\[\033[38;5;12m\]\h\[\033[38;5;196m\]:[\[\033[38;5;46m\]\w\[\033[38;5;196m\]]\[\033[38;5;14m\]\n\$\[$(tput sgr0)\]"'
      state: present
      insertafter: EOF
    with_items:
     - { line: 'PS1="\n\[\033[38;5;196m\](っ▀¯▀)つ\[\033[38;5;196m\]@\[\033[38;5;12m\]\h\[\033[38;5;196m\]:[\[\033[38;5;46m\]\w\[\033[38;5;196m\]]\[\033[38;5;14m\]\n\$\[$(tput sgr0)\]"' }

  - name: "Setup S1 for Default User"
    become: yes
    become_user: root
    tags: example1
    lineinfile:
      path: /home/zalatschenko/.bashrc
      line: 'PS1="\n\[\033[38;5;10m\](っ•́｡•́)♪♬ \[\033[38;5;196m\]@\[\033[38;5;12m\]\h\[\033[38;5;196m\]:[\[\033[38;5;46m\]\w\[\033[38;5;196m\]]\[\033[38;5;14m\]\n\$\[$(tput sgr0)\]"'
      state: present
      insertafter: EOF
    with_items: 
     - { line: 'PS1="\n\[\033[38;5;10m\](っ•́｡•́)♪♬ \[\033[38;5;196m\]@\[\033[38;5;12m\]\h\[\033[38;5;196m\]:[\[\033[38;5;46m\]\w\[\033[38;5;196m\]]\[\033[38;5;14m\]\n\$\[$(tput sgr0)\]"' }

  - name: apt -y update
    command: apt -y update

  - name: install python apt package
    command: apt install python3-apt

  - name: install python3-pip
    command: apt -y install python3-pip
    
  - name: install python-dev
    command: apt -y install python3-dev

  - name: build-essential
    command: apt -y install build-essential
