name: Codecov
on:
  # Triggers this Action on push or pull request events on the "main" branch and when manually requested from the "Actions" tab
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy_code:
    runs-on: 
    steps:
      - name: uploader
        run: |
          git clone -b main git@github.com:heimauto2020/ansible_os_management.git original
          cd original
          curl -Os https://uploader.codecov.io/latest/linux/codecov chmod +x codecov ./codecov
          chmod +x codecov
          ./codecov